#!/bin/bash

run_logic() {
    if [[ "$c" == "1" ]];
    then
        if [[ -z "$s" ]];
        then read -r -p "Подстрока: " s; fi
        if [[ "$t" == *"$s"* ]];
        then
            echo "Подстрока существует"
            apos="${t%%"$s"*}"
            echo "Позиция начала (с 0): ${#apos}"
        else
            echo "Не найдено"
        fi

    elif [[ "$c" == "2" ]];
    then
        if [[ -z "$a" ]];
        then read -r -p "Старт: " a; fi
        if [[ -z "$b" ]];
        then read -r -p "Длина: " b; fi
        echo "${t:$a:$b}"

    elif [[ "$c" == "3" ]];
    then
        if [[ -z "$s" ]];
        then read -r -p "Что: " s;
        fi
        if [[ -z "$r" ]];
        then read -r -p "На что: " r;
        fi
        echo "${t//"$s"/"$r"}"

    elif [[ "$c" == "4" ]];
    then
        if [[ -z "$d" ]];
        then
            echo "1. Из середины"
            echo "2. С начала"
            echo "3. С конца"
            read -r -p "Выбор: " d
        fi

        if [[ "$d" == "1" ]];
        then
            if [[ -z "$a" ]];
            then
            read -r -p "Старт: " a;
            fi
            if [[ -z "$b" ]];
            then
            read -r -p "Длина: " b;
            fi
            echo "${t:0:$a}${t:$((a + b))}"
        elif [[ "$d" == "2" ]];
        then
            if [[ -z "$b" ]];
            then read -r -p "Кол-во: " b;
            fi
            echo "${t:$b}"
        elif [[ "$d" == "3" ]];
        then
            if [[ -z "$b" ]];
            then read -r -p "Кол-во: " b;
            fi
            echo "${t:0:${#t}-b}"
        fi

    elif [[ "$c" == "5" ]]; then
        if [[ -z "$d" ]]; then
            echo "1. В начало"
            echo "2. В конец"
            echo "3. В определенную позицию"
            read -r -p "Выбор: " d
        fi

        if [[ "$d" == "1" ]];
        then
            if [[ -z "$s" ]];
            then read -r -p "Что добавить: " s;
            fi
            echo "${s}${t}"
        elif [[ "$d" == "2" ]];
        then
            if [[ -z "$s" ]];
            then read -r -p "Что добавить: " s;
            fi
            echo "${t}${s}"
        elif [[ "$d" == "3" ]];
        then
            if [[ -z "$a" ]];
            then read -r -p "Позиция (индекс с 0): " a;
            fi
            if [[ -z "$s" ]];
            then read -r -p "Что добавить: " s;
            fi
            echo "${t:0:$a}${s}${t:$a}"
        fi
    fi
}

if [[ $# -gt 0 ]];
then
    t="$1"
    c="$2"

    case "$c" in
        1) s="$3" ;;
        2) a="$3"; b="$4" ;;
        3) s="$3"; r="$4" ;;                                                        #Тяжко
        4|5) d="$3"; a="$4"; b="$5"; s="$5"
             if [[ "$d" == "2" || "$d" == "3" ]];
             then b="$4";
             fi
             if [[ "$c" == "5" && "$d" == "3" ]];
             then a="$4"; s="$5";
             fi
             ;;
    esac

    run_logic
else
    read -r -p "Строка: " t
    echo "1) Поиск"                                               # ==============================================================================
    echo "2) Срез"                                                # ПЕРЕМЕННЫЕ СКРИПТА:
    echo "3) Замена"                                              # $t — исходный текст      $c — выбор главного меню      $s — искомое слово
    echo "4) Удаление"                                            # $apos — текст до слова   $bpos — длина текста $apos    $cpos — длина слова $s
    echo "5) Добавление"                                          # $a — стартовая позиция   $b — количество символов      $r — новый текст
    read -r -p "Выбор: " c                                        # $d — вариант действия (для удаления или добавления)
                                                                  # ==============================================================================
    run_logic
fi

