#!/bin/bash

read -p "Строка: " t

echo "1) Поиск"
echo "2) Срез"
echo "3) Замена"
echo "4) Удаление"
read -p "Выбор: " c

if [[ "$c" == "1" ]];
then
    read -p "Подстрока: " s
    if [[ "$t" == *"$s"* ]];
    then
        echo "Подстрока существует"
    apos=$(echo "$t" | grep -o ".*$s")
    bpos=$(echo "$apos | wc -m)"

    else
        echo "Не найдено"
    fi

elif [[ "$c" == "2" ]];
then
    read -p "Старт: " a
    read -p "Длина: " b
    echo "${t:$a:$b}"

elif [[ "$c" == "3" ]];
then
    read -p "Что: " s
    read -p "На что: " r
    echo "${t//$s/$r}"

elif [[ "$c" == "4" ]];
then
    echo "1. Из середины"
    echo "2. С начала"
    echo "3. С конца"
    read -p "Выбор: " d

    if [[ "$d" == "1" ]];
    then
        read -p "Старт: " a
        read -p "Длина: " b
        echo "${t:0:$a}${t:$((a + b))}"
    elif [[ "$d" == "2" ]];
    then
        read -p "Кол-во: " b
        echo "${t:$b}"
    elif [[ "$d" == "3" ]];
    then
        read -p "Кол-во: " b
        echo "${t:0:${#t}-b}"
    fi
fi
