#!/bin/bash

run_logic() {
    if [[ "$c" == "search" ]];
    then
        if [[ -z "$s" ]];
        then read -r -p "Подстрока: " s;
        fi
        if [[ "$t" == *"$s"* ]];
        then
            echo "Подстрока существует"
            apos="${t%%"$s"*}"
            echo "Позиция начала (с 0): ${#apos}"
        else
            echo "Не найдено"
        fi

    elif [[ "$c" == "slice" ]];
    then
        if [[ -z "$a" ]];
        then read -r -p "Старт: " a;
        fi
        if [[ -z "$b" ]];
        then read -r -p "Длина: " b;
        fi
        echo "${t:$a:$b}"

    elif [[ "$c" == "replace" ]];
    then
        if [[ -z "$s" ]];
        then read -r -p "Что: " s;
        fi
        if [[ -z "$r" ]];
        then read -r -p "На что: " r;
        fi
        echo "${t//"$s"/"$r"}"

    elif [[ "$c" == "delete" ]];
    then
        if [[ -z "$d" ]];
        then
            echo "mid) Из середины"
            echo "start) С начала"
            echo "end) С конца"
            read -r -p "Выбор: " d
        fi

        if [[ "$d" == "mid" ]];
        then
            if [[ -z "$a" ]];
            then
            read -r -p "Старт: " a;
            fi
            if [[ -z "$b" ]];
            then
            read -r -p "Длина: " b;
            fi
            echo "${t:0:$a}${t:$((a + b))}"
        elif [[ "$d" == "start" ]];
        then
            if [[ -z "$b" ]];
            then read -r -p "Кол-во: " b;
            fi
            echo "${t:$b}"
        elif [[ "$d" == "end" ]];
        then
            if [[ -z "$b" ]];
            then
             read -r -p "Кол-во: " b;
            fi
            echo "${t:0:${#t}-b}"
        fi

   elif [[ "$c" == "insert" ]];
   then
        if [[ -z "$d" ]];
        then
            echo "start) В начало"
            echo "end) В конец"
            echo "pos) В определенную позицию"
            read -r -p "Выбор: " d
        fi

        if [[ "$d" == "start" ]];
        then
            if [[ -z "$s" ]];
            then read -r -p "Что добавить: " s;
            fi
            echo "${s}${t}"
        elif [[ "$d" == "end" ]];
        then
            if [[ -z "$s" ]];
            then read -r -p "Что добавить: " s;
            fi
            echo "${t}${s}"
        elif [[ "$d" == "pos" ]];
        then
            if [[ -z "$a" ]];
            then read -r -p "Позиция (индекс с 0): " a;
            fi
            if [[ -z "$s" ]];
            then read -r -p "Что добавить: " s;
            fi
            echo "${t:0:$a}${s}${t:$a}"
        fi
fi
}

if [[ $# -gt 0 ]];
then
    t="$1"
    c="$2"

       case "$c" in
        search) s="$3" ;;
        slice) a="$3"; b="$4" ;;
        replace) s="$3"; r="$4" ;;
        delete)
            d="$3"
            if [[ "$d" == "mid" ]];
            then a="$4"; b="$5";
             fi
            if [[ "$d" == "start" || "$d" == "end" ]];
             then b="$4";
             fi
            ;;
        insert)
            d="$3"
            if [[ "$d" == "start" || "$d" == "end" ]];
             then s="$4";
             fi
            if [[ "$d" == "pos" ]];
             then a="$4"; s="$5";
              fi
            ;;
    esac


    run_logic
else
    read -r -p "Строка: " t
    echo "search) Поиск"                                          # ==============================================================================
    echo "slice) Срез"                                            # ПЕРЕМЕННЫЕ СКРИПТА:
    echo "replace) Замена"                                        # $t — исходный текст      $c — выбор главного меню      $s — искомое слово
    echo "delete) Удаление"                                       # $apos — текст до слова   $bpos — длина текста $apos    $cpos — длина слова $s
    echo "insert) Добавление"                                     # $a — стартовая позиция   $b — количество символов      $r — новый текст
    read -r -p "Выбор: " c                                        # $d — вариант действия (для удаления или добавления)
                                                                  # ==============================================================================
    run_logic
fi
